# Generated by Django 2.2.7 on 2019-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('class_type', models.CharField(choices=[('مزون دار', 'مزون دار'), ('عادی', 'عادی'), ('غیره', 'غیره'), ('جدید', 'جدید')], max_length=20)),
            ],
        ),
    ]
