# Generated by Django 2.2.7 on 2019-12-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='customer.CustomerType'),
        ),
    ]
