# Generated by Django 2.2.7 on 2019-12-10 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_create_customer_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='customer.CustomerType'),
        ),
    ]
