# Generated by Django 2.2.7 on 2019-12-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20191210_0723'),
        ('customer', '0004_auto_20191210_1052'),
    ]

    operations = [
    ]
