# Generated by Django 2.2.7 on 2019-12-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
        ('bill', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='specialproductsdiscount',
            name='products',
            field=models.ManyToManyField(related_name='special_discounts', to='product.Product'),
        ),
        migrations.AddField(
            model_name='specialproductdiscount',
            name='customers',
            field=models.ManyToManyField(related_name='special_discounts', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='ourpayment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bill.SupplierBill'),
        ),
        migrations.AddField(
            model_name='ourpayment',
            name='cheque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bill.OurCheque'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bill.Bill'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='cheque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bill.CustomerCheque'),
        ),
        migrations.AddField(
            model_name='customercheque',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cheques', to='customer.Customer'),
        ),
    ]
