# Generated by Django 2.2.7 on 2019-12-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20191204_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='used_points',
            field=models.IntegerField(default=0),
        ),
    ]
