# Generated by Django 2.1.15 on 2020-01-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20191216_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('remained', 'remained')], default='remained', max_length=10),
        ),
    ]
