# Generated by Django 2.2.7 on 2019-12-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20191210_0748'),
        ('bill', '0003_auto_20191210_1059'),
    ]

    operations = [
    ]
