# Generated by Django 2.1.15 on 2020-01-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20200112_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbillitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.SupplierBill'),
        ),
    ]
