# Generated by Django 2.1.15 on 2020-01-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_auto_20200112_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierbillitem',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='supplierbillitem',
            name='currency_price',
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='currency',
            field=models.CharField(choices=[('ریال', 'ریال'), ('درهم', 'درهم'), ('دلار', 'دلار'), ('روپیه', 'روپیه'), ('یوان', 'یوان')], default='ریال', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='currency_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('remained', 'remained')], default='remained', max_length=32),
        ),
    ]
