# Generated by Django 2.2.7 on 2019-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_auto_20191211_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialdiscount',
            name='straight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierbillitem',
            name='currency_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supplierbillitem',
            name='raw_price',
            field=models.IntegerField(),
        ),
    ]
