# Generated by Django 2.1.15 on 2020-02-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20200112_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
    ]
