# Generated by Django 2.1.15 on 2020-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_billcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('cheque', 'cheque'), ('cash', 'cash'), ('card', 'card')], default='cash', max_length=10),
        ),
    ]
