# Generated by Django 2.1.15 on 2020-02-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_bill_closande'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbill',
            name='bill_code',
            field=models.IntegerField(default=0),
        ),
    ]
