# Generated by Django 2.2.7 on 2019-12-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgb', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProductId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('selling_price', models.IntegerField()),
                ('buying_price', models.IntegerField()),
                ('stock_amount', models.FloatField()),
                ('background_color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bg_products', to='product.Color')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='branch.Branch')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.Design')),
                ('design_color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='design_products', to='product.Color')),
                ('f_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.FType')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.Material')),
            ],
        ),
    ]
