# Generated by Django 2.1.15 on 2020-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191218_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='productid',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
