# Generated by Django 2.1.15 on 2020-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='full_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='store',
            field=models.CharField(blank=True, max_length=60, verbose_name='store'),
        ),
    ]
