# Generated by Django 2.1.15 on 2020-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20200210_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
